CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;


DROP TABLE IF EXISTS data;
DROP TABLE IF EXISTS langue;

CREATE TABLE langue(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom text
);

CREATE TABLE data(
    PRIMARY KEY(langue, sens),
    langue int REFERENCES langue(id),
    sens text,
    mots text
);

CREATE OR REPLACE FUNCTION id_langue(l langue.nom%TYPE)
    RETURNS SETOF langue.id%TYPE AS
    $$
        SELECT id FROM langue WHERE nom = l
    $$
    LANGUAGE SQL
    STABLE;