CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

DROP TABLE IF EXISTS data;
DROP TABLE IF EXISTS langue;
DROP TABLE IF EXISTS historyModif;

CREATE TABLE langue(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom text
);

CREATE TABLE data(
    UNIQUE (langue, sens, date_creation),
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    langue int REFERENCES langue(id),
    sens int,
    date_creation TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    mots text,
    numeroPage int
);


CREATE OR REPLACE FUNCTION id_langue(l langue.nom%TYPE)
    RETURNS SETOF langue.id%TYPE AS
    $$
        SELECT id FROM langue WHERE nom = l
    $$
    LANGUAGE SQL
    STABLE;

-- SELECT langue.nom, data.sens, data.mots, data.numeroPage, data.date_creation
-- FROM data JOIN langue ON (data.langue = langue.id);


DROP VIEW IF EXISTS data_current;
CREATE OR REPLACE VIEW data_current AS (
SELECT nom as nom_langue, langue.id as id_langue, sens, mots, numeroPage 
FROM data JOIN langue ON data.langue = langue.id
WHERE data.date_creation IN (
    SELECT max(data.date_creation) AS id
    FROM data
    GROUP BY langue, sens)
);